name: Trotsky Docs

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build Trotsky
        run: yarn build

      - name: API documentation
        run: yarn doc:api

      - name: Build documentation
        run: yarn doc:build

      - name: Upload documentation artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/.vitepress/dist/

      - name: Deploy artifact to Github Pages
        uses: actions/deploy-pages@v4